// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "stack/include/ember.h"
#include <stdint.h>
#include "rail.h"
#include "rail_types.h"
#include "rail_ieee802154.h"


// Templates from the callbacks info files
